### ISSUE TITLE
Emotions1 behavior unclear

### ISSUE THREAD

**Issue by vbogdev** [cse110-sp23-group6/SixthSense#88]
If you select next page on emotions1, it will save your choice, however, if you never get a reading and go back to the choose your fortunes page or exit out of the page, the choice is still kept. However, if you are on the emotions2 page and use the back button, you will be able to modify your choice for emotions1. Not a very big issue, but makes website inconsistent as it means in some cases you can change emotions1 while in other cases you cant.

**Comment by prishaanand** [comment]
finished
